### ISSUE TITLE
nelify-cms, next stack to aws

### ISSUE THREAD

**Issue by ahmedshakeel083** [robinpokorny/netlify-cms-now#1]
is there a way i can deploy the netlify cms and next site to AWS ? is there any docker availabel for this !
kindly suggest

**Comment by robinpokorny** [comment]
Hey @ahmedshakeel083, I think this is a general question about next.js. A quick googling got me this article, which looks reasonable:
https://codedaily.io/tutorials/184/Deploy-a-NextJS-App-With-Serverless-to-AWS-Lambda

**Comment by ahmedshakeel083** [comment]
i am using ur repo for oauth2 for netlify cms backend login

https://github.com/robinpokorny/netlify-cms-now/blob/master/api/_lib/oauth2.ts

on line 4 i m geting "Property 'create' does not exist on type 'typeof import("/home/shahme/react-bootcamp/nextjs-netlify-blog/node_modules/
@types/simple-oauth2
/index")'"

can u suggest a wirkaround for this , and  one more thing if u can assist with , i am using GITLAB for backend login , this will work for my project ?

**Comment by robinpokorny** [comment]
Hey, I'd suggest installing the package versions as defined in yarn.lock first before updating to newer versions.

This solution will not work with GitLab.

**Comment by ahmedshakeel083** [comment]
Can u kindly suggest me how to do the same we are doing in this repo to auth netlify-cms backend via gitlab

i have to submit this task as i m under deadline, i am researching a lot but i m not getting any examples to follow.

thanks for ur time

**Comment by robinpokorny** [comment]
Sorry, I do not use GitLab, you can try following this guide and adjusting accordingly: https://docs.gitlab.com/ce/api/oauth2.html#authorization-code-flow

**Comment by ahmedshakeel083** [comment]
thank u
